name: calculator_app
description: "A new Flutter calculator app."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.18.0 <3.0.0" # Adjust the SDK version range as needed

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
